Crea tarea 5a
facums/introduccion-a-js pull request #1
Opened 2021-07-04 20:35 UTC by facums

Se agrego otra folder con la tarea 5 inciso a

2021-07-08 10:03 UTC, fsodano requested changes

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5a/index.html
> +        <input type="reset" onclick="document.location.reload(true)">
esto va en el JS, no mezcles markup con scripts, es más difícil debuggear el comportamiento de una página si no.

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5a/tarea-clase-5a.js
> +    document.querySelector('h1').textContent = `Bienvenido ${userData[0]}!`;
acá estás asumiendo que la posición 0 contiene el nombre, me parecería mejor que crees un mapa (un objeto) en vez de un array, para este caso.

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +    let $clone = $template.cloneNode(true);             // create clone node
Ojo con los comentarios redundantes, `//create clone node` no aporta ninguna información que leer que ejecutás `cloneNode` no te de.

Los comentarios no están atados a ninguna validación por parte del IDE por lo tanto se dice que pueden "empezar a mentir", porque podés actualizar tu código (y que funcione) y nunca tocar los comentarios y ahora van a estar fuera de sintonía.

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +    let $aux = $clone.getElementsByTagName('input');  // auxiliar variable for all inputs within <form>
en vez de `$aux` ponele el nombre que representa lo que contiene esta variable, por ejemplo `$videoInputs`.

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +const $submitButton = document.querySelector('#submit-button');
En general los nombres deberían estar atados al dominio, en vez de `$addButton` sería `$addVideo`, por ejemplo. Entonces después te queda más legible cuando definas `$addVideo.onclick = ...`

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +    const $template = document.querySelector('.template');
Un mejor nombre sería `$videoTemplate`

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +    }
si te parece que hace falta aclarar esto, lo podés poner en otra función que explicite lo que estás haciendo y borrar el comentario.

```
function resetVideoInputs(inputs){
   ...
}
```

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +    document.querySelector('.time-calculator-form').appendChild($clone);    // append to <form>
por qué clase y no id? El comentario está de más, `appendChild` deja en claro lo que estás haciendo

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +    let $clone = $template.cloneNode(true);             // create clone node
Al clon del $template deberías quitarle la clase `.template`, me parece

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +    const $template = document.querySelectorAll('.template');
Si bien esto funciona, semánticamente no tiene sentido que elijas todos los templates porque debería existir sólo 1.

Lo que te recomiendo que hagas es que el elemento `#template` empiece escondido y lo vayas clonando sin el ID, y le agregues una clase `video`, entonces después cuando quieras borrar un video buscás elementos con clase `.video` y no `.template`.

Por otro lado, hay un selector que te permite elegir directamente el último elemento o el elemento X, podés fijarte en MDN `:nth-child` o `:nth-of-type` ó `:last-child` así no te hace falta elegir TODOS y después remover sólo 1.

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +$submitButton.onclick = function(){
este botón estaría mejor que se llame por lo que hace "$calculateTime" o algo así.

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +function calculate(){
fijate que como el nombre de la función se queda corto (calculate qué?) te hace falta poner un comentario, si le ponés `calculateVideosTotalTime` no queda duda de lo que hace la función, y no te hace falta el comentario.

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +    const $template = document.querySelectorAll('.template');
no te hace falta agarrar estos elementos, porque podés asumir que `$hoursArray`, `$minutesArray` y `$secondsArray` van a tener la misma longitud (o sea que podés usar cualquiera de esos para recorrerlo y utilizar el índice `i` como hacés ahora con `$template` (que de hecho debería ser `$templates` porque son muchos, no sólo uno!).

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5c/index.html
> +        <li></li>
estaría mejor que crees los inputs en vez de que sea predefinido

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5c/index.html
> +    <ol id="list-random-number" start="0">
el ID debería estar en plural, y los atributos que guardan información arbitraria se conocen como data- attributes, en este caso sería `data-start`, pero igual no creo que le corresponda al HTML definir desde dónde empieza, eso es lógica que va en JS.

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5c/index.html
> +        <em id="em-average-number">El promedio es </em><br>
los `ids` deberían ser independientes del elemento que los contiene, en este caso debería ser sólo `average-number`, si el día de mañana querés usar un `strong` para mostrar el resultado, no te hace falta ir cambiando todos los IDs.

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5c/tarea-clase-5c.js
> +const $createButton = document.querySelector('#create-button');
createQuéCosa?

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5c/tarea-clase-5c.js
> +function average(){
la función `calculateAverage` (siempre con un verbo en infinitivo por delante) debería tomar como parámetro un array de números, no debería saber del DOM.

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5c/tarea-clase-5c.js
> +    $text.textContent += (total / $items.length).toFixed(2);
Esta función debería devolver sólo un número, quien lalma a `calculateAverage` decide qué hacer con el resultado (mostrarlo en un console.log, en un elemento, en un alert, etc.)

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5c/tarea-clase-5c.js
> +function smaller(){
`calculateSmallestNumber`

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5c/tarea-clase-5c.js
> +function larger(){
`calculateLargestNumber`

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5c/tarea-clase-5c.js
> +function frequent(){
`calculateMostFrequent`

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5c/tarea-clase-5c.js
> +        $text.textContent += 'ninguno';
ojo con el Spanglish

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5c/tarea-clase-5c.js
> +    numbers = quickSort(numbers);
no te hace falta ordenarlos de antemano para calcular el más frecuente

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5c/tarea-clase-5c.js
> +    }
si ya tenés un quicksort, podés agarrar el primer elemento como el más pequeño.

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5c/tarea-clase-5c.js
> +    }
si ya tenés un quicksort, podés tomar el último número como el más grande.

2021-07-08 10:03 UTC, fsodano commented on tareas/clase-5/tarea-clase-5c/tarea-clase-5c.js
> +                Object.assign(frequentNumber, currentNumber);   // copy content inside current to frequent
el comentario está de más!

2021-07-08 10:04 UTC, fsodano commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +function calculate(){
Por otro lado, no está bien que esta función sepa del DOM. La separación de funciones es muy importante en programación. Vos qué necesitás para calcular el tiempo total? Necesitás saber todas las horas, todos los minutos y todos los segundos, y con eso vos te encargás de devolver el cálculo total de horas, minutos y segundos.

La función que debería saber del DOM, y por lo tanto la que tiene que extraer los valores de los inputs es otra. En este ejemplo me parece que iría bien en el `$calculateTime` (`$submitButton`).

2021-07-09 23:31 UTC, fsodano commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +    Object.assign(totalVideo, calculateVideosTotalTime(totalVideo));
más que un Object.assign acá podés hacer un `totalVideo = calculateVideosTotalTime`

2021-07-09 23:32 UTC, fsodano commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +    }
en vez de un loop probá con el operador `%`

2021-07-13 03:33 UTC, fmagallanes97 commented on tareas/clase-5/tarea-clase-5a/index.html
> +        <input type="reset" onclick="document.location.reload(true)">
Ahhh ok, no sabia eso. Tiene sentido

2021-07-13 03:33 UTC, fmagallanes97 commented on tareas/clase-5/tarea-clase-5a/tarea-clase-5a.js
> +    document.querySelector('h1').textContent = `Bienvenido ${userData[0]}!`;
Claro quedaria mejor, ya lo solucione de esta manera

2021-07-13 03:34 UTC, facums commented on tareas/clase-5/tarea-clase-5c/tarea-clase-5c.js
> +        $text.textContent += 'ninguno';
Perfect jajaj

2021-07-13 03:35 UTC, facums commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +const $submitButton = document.querySelector('#submit-button');
claro queda mucho mas legible, buen tip

2021-07-13 03:39 UTC, facums commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +    let $clone = $template.cloneNode(true);             // create clone node
dale evito los comentarios, solo cuando sea necesario

2021-07-13 03:43 UTC, facums commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +    let $aux = $clone.getElementsByTagName('input');  // auxiliar variable for all inputs within <form>
emm esto lo cambie ocultando al elemento para despues clonarlo, entonces solo tenia que cambiar los atributos

2021-07-13 03:46 UTC, facums commented on tareas/clase-5/tarea-clase-5c/tarea-clase-5c.js
> +    numbers = quickSort(numbers);
En este caso si no lo ordeno, no me devuelve bien el resultado. Habra otra forma mejor de hacerlo? Lo que se me ocurre es otra funcion que vaya contabilizando con un loop un numero en particular

2021-07-13 03:47 UTC, facums commented on tareas/clase-5/tarea-clase-5c/tarea-clase-5c.js
> +    }
Noo jajaja que bolu.. soy. Ya lo solucione!

2021-07-13 03:47 UTC, facums commented on tareas/clase-5/tarea-clase-5c/tarea-clase-5c.js
> +    }
Listo

2021-07-13 04:26 UTC, fmagallanes97 commented on tareas/clase-5/tarea-clase-5c/index.html
> +    <ol id="list-random-number" start="0">
Ahh bueno, tengo que leer sobre data-attributes. Pense que solo cambiaba el indice.
Lo del ID ya esta solucionado

2021-07-13 04:26 UTC, fmagallanes97 commented on tareas/clase-5/tarea-clase-5c/index.html
> +        <li></li>
emm no entedi bien, te referis a que cree una cierta cantidad de inputs? lo que hice fue, un input para preguntar la cantidad de numeros y con eso crear los li dentro del js

2021-07-13 04:26 UTC, fmagallanes97 commented on tareas/clase-5/tarea-clase-5c/index.html
> +        <em id="em-average-number">El promedio es </em><br>
Perfecto! Ya lo solucione de esta manera

2021-07-13 04:26 UTC, facums commented on tareas/clase-5/tarea-clase-5c/tarea-clase-5c.js
> +function average(){
si lo que hice fue ir dividiendo todo en varias funciones lo mas simple posible, si le podes pegar un ojo despues genial

2021-07-13 04:29 UTC, facums commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +    const $template = document.querySelectorAll('.template');
Joya me sirvio una banda esto, lo solucione asi!

2021-07-13 04:34 UTC, facums commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +function calculate(){
Perfecto, dividi en tareas simples cada funcion para que no se mezcle todo. Una que toma todos las entradas, despues otra formatea estos minutos, segundos y horas

2021-07-13 05:09 UTC, facums commented on tareas/clase-5/tarea-clase-5b/tarea-clase-5b.js
> +    }
Listo, ya quedo

2021-07-18 22:31 UTC, merged